name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make

  build-linux:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make
